FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install && npm cache clean --force

# Copy source code (excluding .dockerignore)
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
